services:
  - type: web
    name: evangadi-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: DB_HOST
        value: srv961.hstgr.io
      - key: DB_USER
        value: u804903834_evangadi_user
      - key: DB_PASSWORD
        value: EmebeteYega$$01234
      - key: DB_NAME
        value: u804903834_evangadi_forum
      - key: PORT
        value: 10000
      - key: INIT_DB
        value: true
      - key: SALT_ROUNDS
        value: 10
      - key: JWT_SECRET
        value: DGnkOPLPrObBmeXtTOaUbPLxpBRmSqbuFJH
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: biniyamtedla30@gmail.com
      - key: EMAIL_APP_PASSWORD
        value: jtlrfmsnldeepnum
      - key: FRONTEND_URL
        value: https://forum.amanuelwubneh.com
